-- Auto PiP: float+pin matching windows when their workspace is hidden,
-- restore them when that workspace becomes visible again.

local src = debug.getinfo(1, "S").source
if src:sub(1, 1) == "@" then
  src = src:sub(2)
end
local plugin_dir = src:match("^(.*)/") or "."

local home = os.getenv("HOME") or ""
local state_home = os.getenv("XDG_STATE_HOME")
if state_home == nil or state_home == "" then
  state_home = home .. "/.local/state"
end
local state_dir = state_home .. "/omarchy/auto-pip"
local state_path = state_dir .. "/state.lua"
local user_config_path = (os.getenv("XDG_CONFIG_HOME") or (home .. "/.config")) .. "/omarchy/auto-pip.lua"

local function copy_table(src_table)
  local out = {}
  for key, value in pairs(src_table) do
    if type(value) == "table" then
      out[key] = copy_table(value)
    else
      out[key] = value
    end
  end
  return out
end

local function merge(base, override)
  if type(override) ~= "table" then
    return base
  end
  local out = copy_table(base)
  for key, value in pairs(override) do
    if type(value) == "table" and type(out[key]) == "table" and key ~= "matches" then
      out[key] = merge(out[key], value)
    else
      out[key] = value
    end
  end
  return out
end

local function load_table(path)
  local file = io.open(path, "r")
  if not file then
    return nil
  end
  file:close()
  local ok, result = pcall(dofile, path)
  if ok and type(result) == "table" then
    return result
  end
  return nil
end

local defaults = load_table(plugin_dir .. "/config.lua") or {}
local cfg = merge(defaults, load_table(user_config_path) or {})

local function log(message)
  if not cfg.debug then
    return
  end
  local file = io.open(state_dir .. "/debug.log", "a")
  if not file then
    return
  end
  file:write(os.date("%H:%M:%S") .. " " .. message .. "\n")
  file:close()
end

local state = load_table(state_path) or { windows = {}, geometry = nil }
if type(state.windows) ~= "table" then
  state.windows = {}
end

local function ensure_state_dir()
  os.execute("mkdir -p " .. string.format("%q", state_dir))
end

local function write_state()
  ensure_state_dir()
  local file = io.open(state_path, "w")
  if not file then
    return
  end
  file:write("-- generated by webtom.auto-pip\nreturn {\n")
  if type(state.geometry) == "table" then
    local saved_w = tonumber(state.geometry.w) or 0
    local saved_h = tonumber(state.geometry.h) or 0
    local max_w = (tonumber(cfg.width) or 480) * 2.5
    local max_h = (tonumber(cfg.height) or 270) * 2.5
    if saved_w >= 80 and saved_h >= 80 and saved_w <= max_w and saved_h <= max_h then
      file:write(string.format(
        "  geometry = { x = %d, y = %d, w = %d, h = %d },\n",
        state.geometry.x or 0,
        state.geometry.y or 0,
        saved_w,
        saved_h
      ))
    end
  end
  file:write("  windows = {\n")
  for address, info in pairs(state.windows) do
    file:write(string.format(
      "    [%q] = { workspace = %q, floating = %s, fullscreen = %s, mode = %q },\n",
      address,
      tostring(info.workspace or ""),
      tostring(info.floating == true),
      tostring(info.fullscreen or 0),
      tostring(info.mode or "window")
    ))
  end
  file:write("  },\n}\n")
  file:close()
end

local function vec(value)
  if type(value) ~= "table" then
    return { x = 0, y = 0 }
  end
  return {
    x = tonumber(value.x or value[1]) or 0,
    y = tonumber(value.y or value[2]) or 0,
  }
end

local function dispatch(dispatcher)
  local ok, err = pcall(function()
    hl.dispatch(dispatcher)
  end)
  if not ok then
    log("dispatch failed: " .. tostring(err))
  end
  return ok
end

local playing_pids = {}

local function fetch_playing_pids()
  local pids = {}
  local list = io.popen("busctl --user list 2>/dev/null")
  if not list then
    return pids
  end
  local players = {}
  for line in list:lines() do
    local name, pid = line:match("^(org%.mpris%.MediaPlayer2%.%S+)%s+(%d+)")
    if name and pid then
      players[#players + 1] = { name = name, pid = tonumber(pid) }
    end
  end
  list:close()

  for _, player in ipairs(players) do
    local quoted = string.format("%q", player.name)
    local prop = io.popen(
      "busctl --user get-property "
        .. quoted
        .. " /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player PlaybackStatus 2>/dev/null"
    )
    if prop then
      local body = prop:read("*a") or ""
      prop:close()
      if body:find('"Playing"', 1, true) then
        if player.pid then
          pids[player.pid] = true
        end
        local instance_pid = player.name:match("instance(%d+)$")
        if instance_pid then
          pids[tonumber(instance_pid)] = true
        end
      end
    end
  end
  return pids
end

local function refresh_playing()
  playing_pids = fetch_playing_pids()
end

local function window_is_playing(win)
  if cfg.only_when_playing == false then
    return true
  end
  local pid = win and tonumber(win.pid)
  if not pid then
    return false
  end
  return playing_pids[pid] == true
end

local function has_tag(win, tag)
  local tags = win.tags
  if type(tags) == "table" then
    for _, name in pairs(tags) do
      if name == tag or name == tag .. "*" then
        return true
      end
    end
  elseif type(tags) == "string" then
    return tags == tag or tags == tag .. "*"
  end
  return false
end

local function is_pip_overlay(win)
  local title = string.lower(win.title or "")
  -- Chromium uses "Picture in picture"; some apps use "Picture-in-Picture".
  return title:find("picture.in.picture") ~= nil
end

local function is_native_pip(win)
  if is_pip_overlay(win) then
    return true
  end
  if has_tag(win, "pip") or has_tag(win, "pop") then
    return true
  end
  return false
end

local function uses_html_pip(win)
  local class_name = win.class or ""
  return class_name:find("youtube%.com__") ~= nil
end

local function send_html_pip(cmd)
  local script = plugin_dir .. "/pip-cmd.py"
  hl.exec_cmd("python3 " .. string.format("%q", script) .. " " .. cmd)
  log("html pip " .. cmd)
end

local function matches(win)
  if not win or not win.mapped then
    return false
  end
  if win.workspace and win.workspace.special then
    return false
  end
  if is_native_pip(win) then
    return false
  end

  local class_name = win.class or ""
  local title = win.title or ""
  local rules = cfg.matches
  if type(rules) ~= "table" then
    return false
  end
  for _, rule in ipairs(rules) do
    if type(rule) == "table" then
      local class_ok = not rule.class or class_name:find(rule.class)
      local title_ok = not rule.title or title:find(rule.title)
      if class_ok and title_ok then
        return true
      end
    end
  end
  return false
end

local function workspace_visible(ws)
  if not ws then
    return false
  end
  if ws.visible == true then
    return true
  end
  for _, monitor in ipairs(hl.get_monitors()) do
    local active = monitor.active_workspace
    if active and active.id == ws.id then
      return true
    end
    local special = monitor.active_special_workspace
    if special and special.id == ws.id then
      return true
    end
  end
  return false
end

local function focused_monitor()
  return hl.get_active_monitor() or hl.get_monitors()[1]
end

local function monitor_layout(monitor)
  local scale = monitor.scale
  if type(scale) ~= "number" or scale <= 0 then
    scale = 1
  end
  local reserved = monitor.reserved or {}
  return {
    x = monitor.x or 0,
    y = monitor.y or 0,
    w = (monitor.width or 0) / scale,
    h = (monitor.height or 0) / scale,
    left = tonumber(reserved.left) or 0,
    right = tonumber(reserved.right) or 0,
    top = tonumber(reserved.top) or 0,
    bottom = tonumber(reserved.bottom) or 0,
  }
end

local function default_geometry(monitor)
  local box = monitor_layout(monitor)
  local width = tonumber(cfg.width) or 480
  local height = tonumber(cfg.height) or 270
  local margin = tonumber(cfg.margin) or 40
  local anchor = cfg.anchor or "bottom-right"
  local x, y
  if anchor == "bottom-left" then
    x = box.x + box.left + margin
    y = box.y + box.h - box.bottom - margin - height
  elseif anchor == "top-right" then
    x = box.x + box.w - box.right - margin - width
    y = box.y + box.top + margin
  elseif anchor == "top-left" then
    x = box.x + box.left + margin
    y = box.y + box.top + margin
  else
    x = box.x + box.w - box.right - margin - width
    y = box.y + box.h - box.bottom - margin - height
  end
  return {
    x = math.floor(x + 0.5),
    y = math.floor(y + 0.5),
    w = math.floor(width + 0.5),
    h = math.floor(height + 0.5),
  }
end

local function clamp_geometry(geometry, monitor)
  local box = monitor_layout(monitor)
  local margin = tonumber(cfg.margin) or 40
  local min_x = box.x + box.left + margin
  local min_y = box.y + box.top + margin
  local max_x = box.x + box.w - box.right - margin - geometry.w
  local max_y = box.y + box.h - box.bottom - margin - geometry.h
  if max_x < min_x then
    max_x = min_x
  end
  if max_y < min_y then
    max_y = min_y
  end
  local x = geometry.x
  local y = geometry.y
  if x < min_x then x = min_x end
  if y < min_y then y = min_y end
  if x > max_x then x = max_x end
  if y > max_y then y = max_y end
  return {
    x = math.floor(x + 0.5),
    y = math.floor(y + 0.5),
    w = geometry.w,
    h = geometry.h,
  }
end

local function plausible_pip_size(width, height, monitor)
  width = tonumber(width) or 0
  height = tonumber(height) or 0
  if width < 80 or height < 80 then
    return false
  end
  -- Omarchy's stock native PiP size, stored if we sampled the overlay too early.
  if width == 600 and height == 338 then
    return false
  end
  if monitor then
    local box = monitor_layout(monitor)
    if box.w > 0 and width > box.w * 0.55 then
      return false
    end
    if box.h > 0 and height > box.h * 0.55 then
      return false
    end
  else
    local want_w = tonumber(cfg.width) or 480
    local want_h = tonumber(cfg.height) or 270
    if width > want_w * 2.5 or height > want_h * 2.5 then
      return false
    end
  end
  return true
end

local function remember_geometry(win)
  if not cfg.remember_position or not win then
    return
  end
  if not is_pip_overlay(win) and not (win.floating and win.pinned) then
    return
  end
  local at = vec(win.at)
  local size = vec(win.size)
  if not plausible_pip_size(size.x, size.y, win.monitor or focused_monitor()) then
    return
  end
  state.geometry = { x = at.x, y = at.y, w = size.x, h = size.y }
end

local function pip_geometry(monitor, index)
  local base = default_geometry(monitor)
  if cfg.remember_position and type(state.geometry) == "table" then
    local saved_w = tonumber(state.geometry.w)
    local saved_h = tonumber(state.geometry.h)
    if plausible_pip_size(saved_w, saved_h, monitor) then
      if state.geometry.x then
        base.x = state.geometry.x
      end
      if state.geometry.y then
        base.y = state.geometry.y
      end
      base.w = saved_w
      base.h = saved_h
    end
  end
  base = clamp_geometry(base, monitor)
  if index > 0 then
    base.x = base.x - (index * 32)
    base.y = base.y - (index * 32)
    base = clamp_geometry(base, monitor)
  end
  return base
end

local function home_workspace_visible(info)
  if not info or not info.workspace or info.workspace == "" then
    return false
  end
  local ws = hl.get_workspace(info.workspace)
  return workspace_visible(ws)
end

local placed_overlays = {}

local function place_overlay(win, index)
  local monitor = focused_monitor()
  if not monitor then
    return
  end
  local geometry = pip_geometry(monitor, index)
  dispatch(hl.dsp.window.resize({
    window = win,
    x = geometry.w,
    y = geometry.h,
    relative = false,
  }))
  dispatch(hl.dsp.window.move({
    window = win,
    x = geometry.x,
    y = geometry.y,
    relative = false,
  }))
  if not has_tag(win, "auto-pip") then
    dispatch(hl.dsp.window.tag({ window = win, tag = "+auto-pip" }))
  end
  dispatch(hl.dsp.window.alter_zorder({ window = win, mode = "top" }))
end

local function restore_window_chrome(win, info)
  if win.pinned then
    dispatch(hl.dsp.window.pin({ window = win, action = "unset" }))
  end
  if has_tag(win, "auto-pip") then
    dispatch(hl.dsp.window.tag({ window = win, tag = "-auto-pip" }))
  end

  local workspace = info and info.workspace
  if workspace and workspace ~= "" then
    dispatch(hl.dsp.window.move({
      window = win,
      workspace = workspace,
      follow = false,
    }))
  end

  local was_floating = info and info.floating == true
  if was_floating then
    if not win.floating then
      dispatch(hl.dsp.window.float({ window = win, action = "set" }))
    end
  else
    if win.floating then
      dispatch(hl.dsp.window.float({ window = win, action = "unset" }))
    end
  end

  local fullscreen = info and tonumber(info.fullscreen) or 0
  if fullscreen ~= 0 then
    dispatch(hl.dsp.window.fullscreen({ window = win, action = "set" }))
  end
end

local function enter_window_pip(win, index)
  local ws = win.workspace
  if not ws or ws.special then
    return
  end

  if not state.windows[win.address] then
    state.windows[win.address] = {
      workspace = ws.name or tostring(ws.id),
      floating = win.floating == true,
      fullscreen = win.fullscreen or 0,
      mode = "window",
    }
  end

  local monitor = focused_monitor()
  if not monitor then
    return
  end
  local geometry = pip_geometry(monitor, index)

  if (win.fullscreen or 0) ~= 0 then
    dispatch(hl.dsp.window.fullscreen({ window = win, action = "unset" }))
  end
  if not win.floating then
    dispatch(hl.dsp.window.float({ window = win, action = "set" }))
  end
  if not win.pinned then
    dispatch(hl.dsp.window.pin({ window = win, action = "set" }))
  end
  dispatch(hl.dsp.window.resize({
    window = win,
    x = geometry.w,
    y = geometry.h,
    relative = false,
  }))
  dispatch(hl.dsp.window.move({
    window = win,
    x = geometry.x,
    y = geometry.y,
    relative = false,
  }))
  if not has_tag(win, "auto-pip") then
    dispatch(hl.dsp.window.tag({ window = win, tag = "+auto-pip" }))
  end
  dispatch(hl.dsp.window.alter_zorder({ window = win, mode = "top" }))
  log("enter window pip " .. win.address)
end

local function enter_html_pip(win)
  local ws = win.workspace
  if not ws or ws.special then
    return
  end

  local home = ws.name or tostring(ws.id)
  if not state.windows[win.address] then
    state.windows[win.address] = {
      workspace = home,
      floating = false,
      fullscreen = win.fullscreen or 0,
      mode = "html",
    }
  else
    state.windows[win.address].mode = "html"
  end

  -- If a previous version floated the whole YouTube app, put it back first.
  if win.floating or win.pinned then
    restore_window_chrome(win, state.windows[win.address])
  end

  send_html_pip("enter")
  log("enter html pip " .. win.address .. " home=" .. home)
end

local function enter_pip(win, index)
  if uses_html_pip(win) then
    enter_html_pip(win)
  else
    enter_window_pip(win, index)
  end
end

local function leave_pip(win, info)
  local mode = info and info.mode or "window"
  if mode == "html" or uses_html_pip(win) then
    send_html_pip("exit")
    if win.floating or win.pinned then
      restore_window_chrome(win, info)
    elseif info and info.workspace and info.workspace ~= "" then
      dispatch(hl.dsp.window.move({
        window = win,
        workspace = info.workspace,
        follow = false,
      }))
    end
  else
    remember_geometry(win)
    restore_window_chrome(win, info)
  end

  state.windows[win.address] = nil
  log("leave pip " .. win.address .. " mode=" .. mode)
end

local busy = false

local function restore_focus(address)
  if not address then
    return
  end
  local win = hl.get_window("address:" .. address)
  if win then
    dispatch(hl.dsp.focus({ window = win }))
  end
end

local function reconcile()
  if busy then
    return
  end
  if cfg.enabled == false then
    if next(state.windows) then
      busy = true
      for _, win in ipairs(hl.get_windows()) do
        local info = state.windows[win.address]
        if info then
          leave_pip(win, info)
        end
      end
      state.windows = {}
      write_state()
      busy = false
    end
    return
  end

  busy = true
  local previous = hl.get_active_window()
  local previous_address = previous and previous.address or nil
  local entered = false
  local left = false
  local alive = {}
  local pip_index = 0

  for _, win in ipairs(hl.get_windows()) do
    local info = state.windows[win.address]
    local eligible = matches(win) or info ~= nil
    if eligible then
      alive[win.address] = true
      local home_visible
      if info then
        home_visible = home_workspace_visible(info)
      else
        home_visible = workspace_visible(win.workspace)
      end
      local playing = window_is_playing(win)
      local html = uses_html_pip(win) or (info and info.mode == "html")
      if home_visible then
        if info then
          leave_pip(win, info)
          left = true
        end
      elseif playing then
        if info and not html then
          remember_geometry(win)
        end
        local already
        if html then
          already = info ~= nil and info.mode == "html"
        else
          already = win.floating and win.pinned and info ~= nil
        end
        if not already then
          enter_pip(win, pip_index)
          entered = true
        end
        pip_index = pip_index + 1
      else
        if info then
          leave_pip(win, info)
          left = true
        end
      end
    end
  end

  local overlay_index = 0
  local seen_overlays = {}
  local html_active = false
  for _, info in pairs(state.windows) do
    if info.mode == "html" then
      html_active = true
      break
    end
  end
  for _, win in ipairs(hl.get_windows()) do
    if is_pip_overlay(win) then
      seen_overlays[win.address] = true
      if html_active then
        if placed_overlays[win.address] then
          remember_geometry(win)
        else
          place_overlay(win, overlay_index)
          local size = vec(win.size)
          local want = pip_geometry(focused_monitor() or win.monitor, overlay_index)
          if math.abs(size.x - want.w) <= 8 and math.abs(size.y - want.h) <= 8 then
            placed_overlays[win.address] = true
          end
        end
        overlay_index = overlay_index + 1
      end
    end
  end
  for address, _ in pairs(placed_overlays) do
    if not seen_overlays[address] then
      placed_overlays[address] = nil
    end
  end
  if html_active and next(seen_overlays) == nil then
    send_html_pip("enter")
  end

  for address, _ in pairs(state.windows) do
    if not alive[address] then
      state.windows[address] = nil
    end
  end

  write_state()
  busy = false

  if (entered or left) and previous_address then
    local current = hl.get_active_window()
    if not current or current.address ~= previous_address then
      restore_focus(previous_address)
    end
  end
end

local function tick()
  refresh_playing()
  reconcile()
end

if type(state.geometry) == "table"
    and not plausible_pip_size(state.geometry.w, state.geometry.h, focused_monitor()) then
  state.geometry = nil
end

if o and o.window then
  local margin = tonumber(cfg.margin) or 40
  local width = tonumber(cfg.width) or 480
  local height = tonumber(cfg.height) or 270
  o.window({ tag = "auto-pip" }, {
    tag = "-default-opacity",
    opacity = "1 1",
    keep_aspect_ratio = true,
    no_dim = true,
  })
  -- Last matching rule wins. Override Omarchy's stock PiP (600x338, top-right).
  local pip_box = {
    size = { width, height },
    move = {
      "(monitor_w-window_w-" .. margin .. ")",
      "(monitor_h-window_h-" .. margin .. ")",
    },
  }
  o.window({ title = "(Picture.?in.?[Pp]icture)" }, pip_box)
  o.window({ tag = "pip" }, pip_box)
end

hl.on("workspace.active", tick)
hl.on("workspace.special_active", tick)
hl.on("workspace.move_to_monitor", tick)
hl.on("monitor.focused", tick)
hl.on("monitor.layout_changed", tick)
hl.on("window.open", tick)
hl.on("window.close", reconcile)
hl.on("window.destroy", reconcile)
hl.on("window.move_to_workspace", tick)
hl.on("window.title", reconcile)
hl.on("window.class", tick)
hl.on("window.fullscreen", reconcile)

hl.timer(function()
  -- omarchy-menu-keybindings stubs `hl`; ipairs on that proxy never ends.
  if type(hl.get_windows) ~= "function" then
    return
  end
  refresh_playing()
  if next(state.windows) then
    for _, win in ipairs(hl.get_windows()) do
      local info = state.windows[win.address]
      if info and info.mode ~= "html" then
        remember_geometry(win)
      elseif is_pip_overlay(win) then
        remember_geometry(win)
      end
    end
  end
  reconcile()
end, { timeout = 500, type = "repeat" })

-- Skip the initial reconcile during the keybindings scan (stubbed `hl`).
if type(hl.get_windows) == "function" then
  tick()
end
